version: "3.7"

services:
  scriptorium:
    container_name: scriptorium
    image: docker_python
    stdin_open: false        # false for `entrypoint` in Dockerfile
    tty: false               # false for `entrypoint` in Dockerfile
    volumes:
      - ./:/home/appuser/app
    build:
      context: .
      dockerfile: ./Dockerfile
