version: "3.7"

services:
  app:
    container_name: scriptorium
    image: docker_python
    stdin_open: true        # false for `entrypoint` in Dockerfile
    tty: true               # false for `entrypoint` in Dockerfile
    volumes:
      - ./:/home/appuser/app
    build:
      context: .
      dockerfile: ./Dockerfile
